spring:
  application:
    name: spring-reactive application
  r2dbc:
    username: postgres
    password: ${PASSWORD}
    name: flex_bk_db
    url: r2dbc:postgresql://localhost:5432/${spring.r2dbc.name}
  profiles:
    active: dev
  flyway:
    user: postgres
    password: ${PASSWORD}
    url: jdbc:postgresql://localhost:5432/${spring.r2dbc.name}
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8085
